### PR TITLE
Optimize the pkgdb2_branch script used when branching

### PR DESCRIPTION
**Pull request by pypingou**
Instead of iterating through the element in the DB and doing one query at a time,
we do two queries:
1/ creates the branch for all the packages
2/ sync the ACLs so that the new branch has the same has rawhide.

With this change, doing a branching 
* on my local machine from 1h45 to 25 minutes
* in stg from 5h+ to 32minutes

### CODE REVIEW

**Comment by ralphbean** [comment]
Nice!  A side effect of this is that we'll need to run the genacls.sh script on pkgs01 afterwards, right? It is usually triggered by a fedmsg message.. but this won't create those messages anymore (if I'm reading it right).

**Comment by ralphbean** [comment]
:+1: here

**Comment by pypingou** [comment]
> A side effect of this is that we'll need to run the genacls.sh script on pkgs01 afterwards, right? 

Likely but we will probably want to run it manually anyway since otherwise branches are created at the first commit in the repo instead of the last commit in the master branch.
(The SOP is updated, on the wiki which is the out-dated location :s)

**Comment by ralphbean** [comment]
Cool, :+1: still.

**Pull request merged**
