### PR TITLE
Requests page

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
I don't understand the ``{{ select }}`` var in the templates.  What is it supposed to represent?

**Comment by pypingou** [comment]
@ralphbean the ``{{ select }}`` precise on the template which item of the menu to highlight and I used this to mark the difference between listing requests for an user (select = 'packagers') and admin (select undefined).

**Comment by ralphbean** [comment]
As mentioned in IRC, I'd also add a comment explaining the differences in the queries.

**Comment by ralphbean** [comment]
Thanks.  :+1: here.

**Comment by pypingou** [comment]
Thanks for the review @ralphbean

**Pull request merged**
