### PR TITLE
Add missing join condition

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by ralphbean** [comment]
@puiterwijk can you explain some what's going on here?

**Comment by ralphbean** [comment]
:+1: after discussion in IRC.   If it it hot-fixed and working now, perhaps @pypingou should have a look too before we merge to develop.

**Comment by puiterwijk** [comment]
The problem is that on the join of PackageListing with PackageListingAcl, there is no join condition.

To give numbers:
PackageListing currently has 218804 records
PackageListingAcl currently has 1735450 records.
This means that without a join condition (which is what I'm adding here), it tries to find distinct rows between 3011786702500 rows.
Which is... quite a few :).

**Comment by puiterwijk** [comment]
This change reduced running time of the query from about 2 minutes down to about 10 seconds.

**Comment by pypingou** [comment]
Thanks for the fix @puiterwijk I was suspecting something like this but had not looked at it yet.

Merging so that I can make a .2 release later today

**Pull request merged**
