### PR TITLE
fix in README

### PR DESCRIPTION
**Pull request by trishnaguha**

### CODE REVIEW

**Comment by pypingou** [comment]
Oh I don't think we'll want to install pkgdb2 in the virtualenv, working in the clone is easier and this way you're sure there are no conflicts between the files you're working on and the files installed in the virtualenv.

That said python-fedora is listed in the ``requirements.txt`` which is processed below, so that entire line about install python-fedora from git could be dropped.

**Comment by trishnaguha** [comment]
@pypingou I have made the change. Can you check it? 
Thank you!

**Comment by pypingou** [comment]
There is a ``cd pkgdb2`` missing then, otherwise the ``pip install -r requirements.txt`` won't work :)

**Comment by trishnaguha** [comment]
@pypingou  Sorry for making this a mess with so many commits.
Thanks :)

**Comment by pypingou** [comment]
Looking good, thanks!

**Comment by trishnaguha** [comment]
Thanks @pypingou :)

**Pull request merged**
