### PR TITLE
Fix pkgdb2.api.extras to be more robust when extracting the summary of a bug

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by puiterwijk** [comment]
Looks sane to me.

**Comment by pypingou** [comment]
Thanks :)

**Comment by puiterwijk** [comment]
I have totally messed up this review :(.

**Comment by puiterwijk** [comment]
Well, the change itself was sane, but the resulting code was not (But it also wouldn't work before this PR).

**Pull request merged**
